/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by the build
try {
  let manifest = self.__WB_MANIFEST;
  if (!manifest) {
    manifest = [];
  }
  precacheAndRoute(manifest);
} catch (e) {
  console.error("SW: Precache error", e);
}

// Fallback for other assets - let browser handle network request
// This prevents SW errors from breaking script loading
// registerRoute(
//   ({ request }) => request.destination === 'script' || request.destination === 'style' || request.destination === 'image',
//   new NetworkOnly()
// );

// Network-first for API calls (don't cache WebSocket or real-time data)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/') && !url.pathname.includes('/ws'),
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 5 }),
    ],
  })
);

// Handle navigation requests - serve index.html for SPA routing
// Exclude /api and /ws paths
const navigationHandler = new NetworkFirst({
  cacheName: 'navigation-cache',
  plugins: [
    new CacheableResponsePlugin({ statuses: [0, 200] }),
  ],
});

registerRoute(
  new NavigationRoute(navigationHandler, {
    denylist: [/^\/api/, /^\/ws/, /^\/r\//],
  })
);

// Skip waiting only when explicitly requested (e.g. by user clicking 'Update')
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
